{
 "title": "Docker Hub Limit",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dockerhub_ratelimit_limit_interval",
    "query": { "query": "dockerhub_ratelimit_limit" }
   },
   {
    "name": "dockerhub_ratelimit_remaining_interval",
    "query": { "query": "dockerhub_ratelimit_remaining" }
   },
   { "name": "dockerhub_username", "query": { "query": "dockerhub_ratelimit_limit" } }
  ]
 },
 "panels": [
  {
   "title": "Utilisateur Docker Hub",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requêtes autorisées",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockerhub_ratelimit_limit" }
   ]
  },
  {
   "title": "Période autorisée",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${dockerhub_ratelimit_limit_interval}"
    }
   ]
  },
  {
   "title": "Requêtes restantes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dockerhub_ratelimit_remaining" }
   ]
  },
  {
   "title": "Période restante",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "${dockerhub_ratelimit_remaining_interval}"
    }
   ]
  },
  {
   "title": "Requêtes utilisées",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((dockerhub_ratelimit_limit - dockerhub_ratelimit_remaining) * 100) / dockerhub_ratelimit_limit"
    }
   ]
  },
  {
   "title": "Évolution du nombre de requêtes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(dockerhub_ratelimit_limit - dockerhub_ratelimit_remaining)",
     "legendFormat": "Requêtes utilisées"
    },
    { "expr": "dockerhub_ratelimit_limit", "legendFormat": "Requêtes autorisées" }
   ]
  }
 ]
}